// Generated by gencpp from file grasping_gym_actions/makeEnvStep.msg
// DO NOT EDIT!


#ifndef GRASPING_GYM_ACTIONS_MESSAGE_MAKEENVSTEP_H
#define GRASPING_GYM_ACTIONS_MESSAGE_MAKEENVSTEP_H

#include <ros/service_traits.h>


#include <grasping_gym_actions/makeEnvStepRequest.h>
#include <grasping_gym_actions/makeEnvStepResponse.h>


namespace grasping_gym_actions
{

struct makeEnvStep
{

typedef makeEnvStepRequest Request;
typedef makeEnvStepResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct makeEnvStep
} // namespace grasping_gym_actions


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::grasping_gym_actions::makeEnvStep > {
  static const char* value()
  {
    return "c712a2155849fa75c27303831b1cb309";
  }

  static const char* value(const ::grasping_gym_actions::makeEnvStep&) { return value(); }
};

template<>
struct DataType< ::grasping_gym_actions::makeEnvStep > {
  static const char* value()
  {
    return "grasping_gym_actions/makeEnvStep";
  }

  static const char* value(const ::grasping_gym_actions::makeEnvStep&) { return value(); }
};


// service_traits::MD5Sum< ::grasping_gym_actions::makeEnvStepRequest> should match 
// service_traits::MD5Sum< ::grasping_gym_actions::makeEnvStep > 
template<>
struct MD5Sum< ::grasping_gym_actions::makeEnvStepRequest>
{
  static const char* value()
  {
    return MD5Sum< ::grasping_gym_actions::makeEnvStep >::value();
  }
  static const char* value(const ::grasping_gym_actions::makeEnvStepRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::grasping_gym_actions::makeEnvStepRequest> should match 
// service_traits::DataType< ::grasping_gym_actions::makeEnvStep > 
template<>
struct DataType< ::grasping_gym_actions::makeEnvStepRequest>
{
  static const char* value()
  {
    return DataType< ::grasping_gym_actions::makeEnvStep >::value();
  }
  static const char* value(const ::grasping_gym_actions::makeEnvStepRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::grasping_gym_actions::makeEnvStepResponse> should match 
// service_traits::MD5Sum< ::grasping_gym_actions::makeEnvStep > 
template<>
struct MD5Sum< ::grasping_gym_actions::makeEnvStepResponse>
{
  static const char* value()
  {
    return MD5Sum< ::grasping_gym_actions::makeEnvStep >::value();
  }
  static const char* value(const ::grasping_gym_actions::makeEnvStepResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::grasping_gym_actions::makeEnvStepResponse> should match 
// service_traits::DataType< ::grasping_gym_actions::makeEnvStep > 
template<>
struct DataType< ::grasping_gym_actions::makeEnvStepResponse>
{
  static const char* value()
  {
    return DataType< ::grasping_gym_actions::makeEnvStep >::value();
  }
  static const char* value(const ::grasping_gym_actions::makeEnvStepResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GRASPING_GYM_ACTIONS_MESSAGE_MAKEENVSTEP_H
