// Generated by gencpp from file grasping_gym_actions/resetEnvRequest.msg
// DO NOT EDIT!


#ifndef GRASPING_GYM_ACTIONS_MESSAGE_RESETENVREQUEST_H
#define GRASPING_GYM_ACTIONS_MESSAGE_RESETENVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace grasping_gym_actions
{
template <class ContainerAllocator>
struct resetEnvRequest_
{
  typedef resetEnvRequest_<ContainerAllocator> Type;

  resetEnvRequest_()
    {
    }
  resetEnvRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::grasping_gym_actions::resetEnvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::grasping_gym_actions::resetEnvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct resetEnvRequest_

typedef ::grasping_gym_actions::resetEnvRequest_<std::allocator<void> > resetEnvRequest;

typedef boost::shared_ptr< ::grasping_gym_actions::resetEnvRequest > resetEnvRequestPtr;
typedef boost::shared_ptr< ::grasping_gym_actions::resetEnvRequest const> resetEnvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::grasping_gym_actions::resetEnvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::grasping_gym_actions::resetEnvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace grasping_gym_actions

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::grasping_gym_actions::resetEnvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grasping_gym_actions::resetEnvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grasping_gym_actions::resetEnvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grasping_gym_actions::resetEnvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grasping_gym_actions::resetEnvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grasping_gym_actions::resetEnvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::grasping_gym_actions::resetEnvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::grasping_gym_actions::resetEnvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::grasping_gym_actions::resetEnvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "grasping_gym_actions/resetEnvRequest";
  }

  static const char* value(const ::grasping_gym_actions::resetEnvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::grasping_gym_actions::resetEnvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::grasping_gym_actions::resetEnvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::grasping_gym_actions::resetEnvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct resetEnvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::grasping_gym_actions::resetEnvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::grasping_gym_actions::resetEnvRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // GRASPING_GYM_ACTIONS_MESSAGE_RESETENVREQUEST_H
