// Generated by gencpp from file grasping_gym_actions/resetEnvResponse.msg
// DO NOT EDIT!


#ifndef GRASPING_GYM_ACTIONS_MESSAGE_RESETENVRESPONSE_H
#define GRASPING_GYM_ACTIONS_MESSAGE_RESETENVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace grasping_gym_actions
{
template <class ContainerAllocator>
struct resetEnvResponse_
{
  typedef resetEnvResponse_<ContainerAllocator> Type;

  resetEnvResponse_()
    : state()
    , success(false)
    , message()  {
    }
  resetEnvResponse_(const ContainerAllocator& _alloc)
    : state(_alloc)
    , success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _state_type;
  _state_type state;

   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::grasping_gym_actions::resetEnvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::grasping_gym_actions::resetEnvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct resetEnvResponse_

typedef ::grasping_gym_actions::resetEnvResponse_<std::allocator<void> > resetEnvResponse;

typedef boost::shared_ptr< ::grasping_gym_actions::resetEnvResponse > resetEnvResponsePtr;
typedef boost::shared_ptr< ::grasping_gym_actions::resetEnvResponse const> resetEnvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::grasping_gym_actions::resetEnvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::grasping_gym_actions::resetEnvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace grasping_gym_actions

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::grasping_gym_actions::resetEnvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grasping_gym_actions::resetEnvResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grasping_gym_actions::resetEnvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grasping_gym_actions::resetEnvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grasping_gym_actions::resetEnvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grasping_gym_actions::resetEnvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::grasping_gym_actions::resetEnvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "088e9c4476fc19677acf3a00f86ee390";
  }

  static const char* value(const ::grasping_gym_actions::resetEnvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x088e9c4476fc1967ULL;
  static const uint64_t static_value2 = 0x7acf3a00f86ee390ULL;
};

template<class ContainerAllocator>
struct DataType< ::grasping_gym_actions::resetEnvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "grasping_gym_actions/resetEnvResponse";
  }

  static const char* value(const ::grasping_gym_actions::resetEnvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::grasping_gym_actions::resetEnvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] state\n\
bool success\n\
string message\n\
\n\
";
  }

  static const char* value(const ::grasping_gym_actions::resetEnvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::grasping_gym_actions::resetEnvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct resetEnvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::grasping_gym_actions::resetEnvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::grasping_gym_actions::resetEnvResponse_<ContainerAllocator>& v)
  {
    s << indent << "state[]" << std::endl;
    for (size_t i = 0; i < v.state.size(); ++i)
    {
      s << indent << "  state[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.state[i]);
    }
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRASPING_GYM_ACTIONS_MESSAGE_RESETENVRESPONSE_H
